# Generated by Django 2.1.7 on 2019-07-18 02:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sciencehistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historynode',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 2, 19, 21, 302000, tzinfo=utc), verbose_name='Modified time'),
            preserve_default=False,
        ),
    ]
