# Generated by Django 3.0.4 on 2020-03-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciencehistory', '0003_auto_20200314_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historynode',
            name='rank',
        ),
        migrations.AlterField(
            model_name='historynode',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='historynode',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Modified time'),
        ),
    ]
