# Generated by Django 3.0.4 on 2020-03-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciencehistory', '0004_auto_20200314_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historynode',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='historynode',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='historynode',
            name='namespaced_key',
            field=models.CharField(default='default', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historynode',
            name='link',
            field=models.CharField(default='http://stic.dothome.co.kr/w/', max_length=150),
        ),
        migrations.AlterField(
            model_name='referringflow',
            name='end',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='referringflow',
            name='start',
            field=models.CharField(max_length=50),
        ),
    ]
