# Generated by Django 3.0.4 on 2020-03-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciencehistory', '0005_auto_20200315_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historynode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historynode',
            name='link',
        ),
        migrations.RemoveField(
            model_name='historynode',
            name='namespaced_key',
        ),
        migrations.AlterField(
            model_name='historynode',
            name='title',
            field=models.CharField(default='default', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='referringflow',
            name='end',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referringflow',
            name='start',
            field=models.CharField(max_length=100),
        ),
    ]
