# Generated by Django 3.1.2 on 2020-10-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sciencehistory', '0010_auto_20201013_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='referringflow',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='sciencehistory.category'),
        ),
    ]
