# Generated by Django 3.1.2 on 2020-10-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sciencehistory', '0011_referringflow_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referringflow',
            name='end',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='endpoint', to='sciencehistory.historynode'),
        ),
        migrations.AlterField(
            model_name='referringflow',
            name='start',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='startpoint', to='sciencehistory.historynode'),
        ),
    ]
