# Generated by Django 3.1.2 on 2020-10-13 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sciencehistory', '0012_auto_20201013_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historynode',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sciencehistory.category'),
        ),
        migrations.AlterField(
            model_name='referringflow',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sciencehistory.category'),
        ),
        migrations.AlterField(
            model_name='referringflow',
            name='end',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='endpoint', to='sciencehistory.historynode'),
        ),
        migrations.AlterField(
            model_name='referringflow',
            name='start',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='startpoint', to='sciencehistory.historynode'),
        ),
    ]
